jobs:  
  - name: runsh-script
    type: runSh
    steps:
      - IN: pipeline_scriptRepo
      - IN: ship_dh
      - IN: sample_img
      - IN: test_params      
      - TASK:
        - script: ./IN/pipeline_scriptRepo/gitRepo/runsh/testscript.sh
      - OUT: test_out_img

  - name: runsh-pre_jobscript
    type: runSh
    steps:
      - IN: pipeline_scriptRepo
      - IN: runsh-script
        switch: off
      - TASK:
        - script: ./IN/pipeline_scriptRepo/gitRepo/runsh/pre_runshjob.sh
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - script: echo 'it is for on_satrt'
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
    # # - script: ./IN/sample-script-3/gitRepo/echo.sh
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
    always:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
