jobs:  
  - name: runshscript
    type: runSh
    steps:
      - IN: pipeline_scriptRepo
      - IN: ship_dh
      - IN: sample_img
      - IN: test_params  
      - IN: t2runsh
      - TASK:
        - script: ./IN/pipeline_scriptRepo/gitRepo/runsh/testscript.sh
      - OUT: test_out_img

  - name: runsh_pre_jobscript
    type: runSh
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
      - script: echo 'it is for on_start'      
    steps:    
      - IN: pipeline_scriptRepo
        switch: off
      - IN: runshscript   
      - IN: same_syncRepos
      - TASK:
        - script: ./IN/pipeline_scriptRepo/gitRepo/runsh/pre_runshjob.sh    
        - script: ./IN/same_syncRepos/gitRepo/script.sh  
        - script: printenv
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
    # # - script: ./IN/sample-script-3/gitRepo/echo.sh
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
    always:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc

  - name: runcliscript
    type: runCLI
    steps:
      
      - IN: pipeline_scriptRepo   
      - IN: ship_dh_cli
      - IN: ship_aws_cli
      - IN: ship_gke_cli
      - IN: ship_ecr_cli
      - IN: ship_gcr_cli
      - IN: ship_quay_cli
      - IN: t3runcli
      - TASK:
        - F2: DF
        - script: ./IN/pipeline_scriptRepo/gitRepo/runcli/accInt.sh 
        - script: printenv
        
  - name: manifest_dep
    type: manifest
    steps:
      - IN: deploy_img       
      - IN: t1
      
  - name: deploy_ddc
    type: deploy    
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
    steps:
      
      - IN: manifest_dep
      - IN: ddc_cluster
      - IN: ddc_dopts
      - TASK: managed   
    on_success:         
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc      
    on_failure:
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc 
